site_name: Kreier Home Lab
site_description: Documentation for my home lab setup
site_url: https://kreier.github.io/homelab/
repo_url: https://github.com/kreier/homelab
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    # - navigation.tabs             # This moves Setup/Servers/Pi to the TOP bar
    - navigation.sections         # This creates the visual groups in the sidebar
    - navigation.expand           # This keeps sub-menus open by default
    - navigation.path             # Breadcrumbs
    - navigation.indexes          # Makes parent titles clickable
    - content.code.copy
    - search.suggest

plugins:
  - search
  - glightbox

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences

nav:
  - Home: index.md
  - Setup: setup.md
  - Machines: 
    - Overview: machines/index.md
    - Penta-GPU server:
      - Hardware: machines/server/hardware.md
      - Software: machines/server/software.md
    - i5-8500T:
      - Hardware: machines/8500/hardware.md
      - Software: machines/8500/software.md
    - Nvidia Jetson Nano:
      - Hardware: machines/jetson/hardware.md
      - Software: machines/jetson/software.md
    - Other devices:
      - Raspberry Pi 4: machines/pi4.md
      - Raspberry Pi 4: machines/pi3.md
      - Rockchip rk3229: machines/rk3229.md
  - Networks:
    - Overview: network/index.md
    - Home Network: network/home.md
  - Services:
    - Home Assistant: services/home-assistant.md
    - Automation n8n: services/n8n.md
    - Pi-hole: services/pihole.md
  - History: history.md
  - Legacy: legacy.md
